"""initial schema

Revision ID: 1f5a15c3d3d9
Revises: 
Create Date: 2025-12-11 00:35:05.270828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f5a15c3d3d9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortener__short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('original_url', sqlmodel.sql.sqltypes.AutoString(length=2048), nullable=False),
    sa.Column('owner_client_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('created_by_user_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('HUMAN', 'SERVICE', 'ANONYMOUS', 'UNKNOWN', name='sourcetype'), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortener__short_urls_code'), 'shortener__short_urls', ['code'], unique=True)
    op.create_index(op.f('ix_shortener__short_urls_created_by_user_id'), 'shortener__short_urls', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shortener__short_urls_original_url'), 'shortener__short_urls', ['original_url'], unique=False)
    op.create_index(op.f('ix_shortener__short_urls_owner_client_id'), 'shortener__short_urls', ['owner_client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortener__short_urls_owner_client_id'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_original_url'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_created_by_user_id'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_code'), table_name='shortener__short_urls')
    op.drop_table('shortener__short_urls')
    # ### end Alembic commands ###
