"""renaming tables

Revision ID: 3be0fd5a85e2
Revises: 50ac7b454741
Create Date: 2025-12-10 23:15:48.263477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '3be0fd5a85e2'
down_revision: Union[str, Sequence[str], None] = '50ac7b454741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortener__short_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('original_url', sa.String(length=2048), nullable=False),
    sa.Column('owner_client_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_type', sa.Enum('HUMAN', 'SERVICE', 'ANONYMOUS', 'UNKNOWN', name='source_type_enum'), server_default='anonymous', nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('extras', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortener__short_urls_code'), 'shortener__short_urls', ['code'], unique=True)
    op.create_index(op.f('ix_shortener__short_urls_created_by_user_id'), 'shortener__short_urls', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_shortener__short_urls_id'), 'shortener__short_urls', ['id'], unique=False)
    op.create_index(op.f('ix_shortener__short_urls_original_url'), 'shortener__short_urls', ['original_url'], unique=False)
    op.create_index(op.f('ix_shortener__short_urls_owner_client_id'), 'shortener__short_urls', ['owner_client_id'], unique=False)
    op.drop_index(op.f('ix_short_urls_code'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_created_by_user_id'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_id'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_original_url'), table_name='short_urls')
    op.drop_index(op.f('ix_short_urls_owner_client_id'), table_name='short_urls')
    op.drop_table('short_urls')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_urls',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=16), nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('owner_client_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('clicks', sa.INTEGER(), nullable=False),
    sa.Column('extras', sqlite.JSON(), nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=9), server_default=sa.text("'anonymous'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_short_urls_owner_client_id'), 'short_urls', ['owner_client_id'], unique=False)
    op.create_index(op.f('ix_short_urls_original_url'), 'short_urls', ['original_url'], unique=False)
    op.create_index(op.f('ix_short_urls_id'), 'short_urls', ['id'], unique=False)
    op.create_index(op.f('ix_short_urls_created_by_user_id'), 'short_urls', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_short_urls_code'), 'short_urls', ['code'], unique=1)
    op.drop_index(op.f('ix_shortener__short_urls_owner_client_id'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_original_url'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_id'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_created_by_user_id'), table_name='shortener__short_urls')
    op.drop_index(op.f('ix_shortener__short_urls_code'), table_name='shortener__short_urls')
    op.drop_table('shortener__short_urls')
    # ### end Alembic commands ###
