"""add source_type to short_urls

Revision ID: 50ac7b454741
Revises: 9874f58b026e
Create Date: 2025-12-09 19:18:08.884905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ac7b454741'
down_revision: Union[str, Sequence[str], None] = '9874f58b026e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_urls', sa.Column('source_type', sa.Enum('HUMAN', 'SERVICE', 'ANONYMOUS', 'UNKNOWN', name='source_type_enum'), server_default='anonymous', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_urls', 'source_type')
    # ### end Alembic commands ###
